<a href="https://colab.research.google.com/github/matheusfs99/Django/blob/master/Labirinto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [19]:
row = int(input('Informe o numero de linhas: '))
col = int(input('Informe o numero de colunas: '))

Informe o numero de linhas: 5
Informe o numero de colunas: 10


In [197]:
tabuleiro = np.zeros(row*col).reshape(row, col)
tabuleiro

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [202]:
x = int(input('Informe a linha do ponto de partida sabendo q a contagem começa em 0: '))
y = int(input('Informe a coluna do ponto de partia sabendo q a contagem começa em 0: '))
inicio = tabuleiro
inicio[x:x+1, y:y+1] = 1 #[primira posicao da linha:ultima posicao da linha +1, primira posicao da coluna:ultima posicao da coluna +1] = novo valor
posicao = np.copy(inicio)
print(inicio)

Informe a linha do ponto de partida sabendo q a contagem começa em 0: 3
Informe a coluna do ponto de partia sabendo q a contagem começa em 0: 3
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [0]:
print(posicao)
while True:
  mov = int(input('Para qual direção você deseja ir?\n [1] - NORTE\n'+
                        ' [2] - SUL\n [3] - LESTE\n [4] - OESTE\n [5] - NORDESTE\n'+
                        ' [6] - NOROESTE\n [7] - SULDESTE\n [8] - SULDOESTE\n [0] - SAIR\n'))
  if mov == 1:
    posicao[x:x+1, y:y+1] = 0
    x -= 1
    posicao[x:x+1, y:y+1] = 2
  elif mov == 2:
    posicao[x:x+1, y:y+1] = 0
    x += 1
    posicao[x:x+1, y:y+1] = 2
  elif mov == 3:
    posicao[x:x+1, y:y+1] = 0
    y -= 1
    posicao[x:x+1, y:y+1] = 2
  elif mov == 4:
    posicao[x:x+1, y:y+1] = 0
    y += 1
    posicao[x:x+1, y:y+1] = 2
  elif mov == 5:
    posicao[x:x+1, y:y+1] = 0
    x -= 1
    y += 1
    posicao[x:x+1, y:y+1] = 2
  elif mov == 6:
    posicao[x:x+1, y:y+1] = 0
    x -= 1
    y -= 1
    posicao[x:x+1, y:y+1] = 2
  elif mov == 7:
    posicao[x:x+1, y:y+1] = 0
    x += 1
    y -= 1
    posicao[x:x+1, y:y+1] = 2
  elif mov == 8:
    posicao[x:x+1, y:y+1] = 0
    x += 1
    y += 1
    posicao[x:x+1, y:y+1] = 2
  elif mov == 0:
    break
  else:
    print('Opção inválida! Selecione uma direção válida.')
  
  print(posicao)